# Generated by Django 3.2.7 on 2022-07-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_cycles_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycles',
            name='contact',
            field=models.IntegerField(default=0),
        ),
    ]
