# Generated by Django 3.2.7 on 2022-07-12 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_cycles_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cycles',
            new_name='cycle',
        ),
    ]
