# Generated by Django 3.2.7 on 2022-07-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_rename_cycles_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
