# Generated by Django 3.2.7 on 2022-07-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_electronic'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='describe',
            field=models.TextField(default='Hari'),
        ),
        migrations.AddField(
            model_name='electronic',
            name='describe',
            field=models.TextField(default='Hari'),
        ),
        migrations.AddField(
            model_name='sport',
            name='describe',
            field=models.TextField(default='Hari'),
        ),
    ]
